# -*- coding: utf-8 -*-
"""stats_random.R

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RxKhd0ZjpLEtuD8VVDX1d5uNneni7uxg

#Generate Random Data


1.  Income (the dependent variable)
2. age (18-65)
3. educational level (no education, lower secondary, secondary, diploma, university)
4. years with current employer 
5. region (west bank, gaza)
6. gender 
7. marital
"""

# libraries
library(janeaustenr)
library(dplyr)
library(stringr)
library(tidytext)
library(tidyverse)
library(class)
library(rpart)
library(rpart.plot)
library(VIM)
library(mice)
library(Metrics)

dataset <- data.frame(income = sample(45:2000, 100000, replace = TRUE),
                      age = sample(18:65, 100000, replace = TRUE),
                      ed_level = sample(c("No Education", "Lower Secondary", "Secondary", "Diploma", "University"), 100000, replace = TRUE),
                      date = sample(2002:2021, 100000, replace = TRUE),
                      region = sample(c("West bank", "Gaza"), 100000, replace = TRUE),
                      gender = sample(c("Male", "Female"), 100000, replace=TRUE),
                      marital = sample(c("Married", "Divorced", "Single"), 100000, replace = TRUE))

summary(dataset)

head(dataset)

# Column Ymiss
dataset <- dataset %>% 
  mutate (Ymiss = case_when(
    income == 50 ~ 200,
    income == 100 ~ NA_real_,
    TRUE ~ as.numeric(income)))

str(dataset)

# Replace 25 % with Nas

dataset <- dataset %>% 
    mutate(Ymiss = replace(Ymiss, which(Ymiss<1500), NA))

head(dataset)

summary(dataset)

str(dataset)

hist(dataset$Ymiss)

# Split the dataset
notNull <- dataset[, 5:8]
Null <- dataset[, 1:4]
set.seed(123)
s_size <- floor(0.66 * nrow(notNull))
train_v <- sample(seq_len(nrow(notNull)), size = s_size)
train <- notNull[train_v, ]
test <- notNull[-train_v, ]

head(train)

# Model
model_fit <- rpart(Ymiss ~., data = train, method = 'class')
summary(model_fit)

# Impute values of Ymiss
val <- md.pattern(test)

#impute values complete case analysis
impute <- mice(test, m=5, maxit = 100, method = 'pmm', seed = 1000)
summary(impute)

head(impute)

# compare and comple
rmspe <- rmse(test$Ymiss, dataset$income)
summary(rmspe)